controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

genre_horreur:
    path: /horreur
    controller: App\Controller\GenreController::horreurAction

genre_romance:
    path: /romance
    controller: App\Controller\GenreController::romanceAction
